export default {
  LOGIN: 'Login',

  HOME: 'Home',
  T_HOME: 'Home',
  B_HOME: 'Bottom Nav Home',
  D_HOME: 'Drawer Home',
  TIMETABLE: 'Timetable',
  NOTIFICATIONS: 'Notifications',
  CREATE_NOTIFICATION: 'Add Notification',
  NOTIFICATION_DETAILS: 'Notification Details',
  TESTS: 'Tests',
  T_EXAMS: 'Tests',
  T_EXAM_CREATE: 'Create Test',
  T_EXAM_DETAILS: 'Test Details',
  TEST_DETAILS: 'Test Details',
  ATTENDANCE: 'Attendance',
  ATTENDANCE_DETAILS: 'Attendance Details',
  T_ATTENDANCE: 'Attendance',
  T_ATTENDANCE_CREATE: 'Mark Attendance',
  MARK_S_ATTENDANCE: 'Mark Scheduled Attendance',
  T_ATTENDANCE_DETAILS: 'Attendance Details',

  ADD_CHILD: 'Add Child',
  ACCOUNTS: 'Accounts',
  ANNOUNCEMENT: 'Announcements',
  ANNOUNCEMENT_DETAILS: 'Announcement Details',
  MONTHLY_TIMETABLE: 'Monthly Timetable',
  ABOUT_US: 'About Us',
  CHANGE_PASSWORD: 'Change Password',
  ON_BOARDING: 'On Boarding',
  SPLASH: 'Splash',
  TAKE_PICTURE: 'Take Picture',
  LOGOUT: 'Logout',
};
